const products = [
    {
      title: 'Product 1',
      price: '1.99',
      image: 'https://source.unsplash.com/random/400x400',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      category: 'shirts',
      stock: 10,
      id: 1,
      initial: 1,
    },
    {
      title: 'Product 2',
      price: '2.99',
      image: 'https://source.unsplash.com/random/400x400',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      category: 'shirts',
      stock:  5,
      id: 2,
      initial: 1,
    },
    {
      title: 'Product 3',
      price: '3.99',
      image: 'https://source.unsplash.com/random/400x400',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      category: 'shirts',
      stock: 3,
      id: 3,
      initial: 1,
    },
    {
      title: 'Product 4',
      price: '3.99',
      image: 'https://source.unsplash.com/random/400x400',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      category: 'shirts',
      stock: 3,
      id: 4,
      initial: 1,
    },
    {
      title: 'Product 5',
      price: '3.99',
      image: 'https://source.unsplash.com/random/400x400',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      category: 'pants',
      stock: 3,
      id: 5,
      initial: 1,
    },
    {
      title: 'Product 6',
      price: '3.99',
      image: 'https://source.unsplash.com/random/400x400',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      category: 'pants',
      stock: 6,
      id: 6,
      initial: 1,
    },
    {
      title: 'Product 7',
      price: '3.99',
      image: 'https://source.unsplash.com/random/400x400',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      category: 'pants',
      stock: 7,
      id: 7,
      initial: 1,
    },
    {
      title: 'Product 8',
      price: '3.99',
      image: 'https://source.unsplash.com/random/400x400',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      category: 'pants',
      stock: 8,
      id: 8,
      initial: 1,
    },
  ]

  const producto4 = {
    title: 'Samsung Galaxy S4 Mini',
    price: '15.99',
    image: 'https://source.unsplash.com/random/400x400',
    stock: 10,
    id: 9,
    initial: 1,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    }

export default products
export {producto4}